#!groovy

def projects = [
    'tailon-docker': 'http://gitea:3000/hvle/tailon-docker.git',
    'boot-external-config': 'http://gitea:3000/hvle/boot-external-config.git'
]

pipeline {

  agent any

  parameters {
    choice(
        name: 'PROJECT',
        //choices: "${projects}.keySet().join('\\n')",
        choices: "tailon-docker\nboot-external-config",
        description: 'Project to release'
    )
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  stages {
    stage('Checkout SCM') {
      steps {
        git url: projects.get(params.PROJECT)
      }
    }
    stage('Release') {
      agent {
        docker {
          image 'maven:3.5.4-jdk-8-alpine'
          args '--net gitea_jenkins_default -v $HOME/.m2:/root/.m2'
          reuseNode true
        }
      }
      steps {
        runMavenGoal "jgitflow:release-start -B -DallowUntracked=true -DautoVersionSubmodules=true -DpushReleases=true -DreleaseBranchVersionSuffix=RC -DnoDeploy=true -DscmCommentPrefix=[jgitflow]"
        //  -Dusername=\'${GIT_USERNAME}\' -Dpassword=\'${GIT_PASSWORD}\'
      }
    }
  }

  post {
    always {
      notifySlack "${currentBuild.currentResult}", "#graylog-notifications"
    }
  }

}
