#!groovy
pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  stages {
    stage('Checkout SCM') {
      steps {
        git url: 'http://gitea:3000/hvle/tailon-docker.git'
      }
    }
    stage('Release') {
      agent {
        docker {
          image 'maven:3.5.4-jdk-8-alpine'
          args '-v $HOME/.m2:/root/.m2 -v $PWD/tailon-docker:/work -w /work'
          reuseNode true
        }
      }
      steps {
        runMavenGoal "jgitflow:release-start -B -DallowUntracked=true -DautoVersionSubmodules=true -DpushReleases=true -DreleaseBranchVersionSuffix=RC -DnoDeploy=true -DscmCommentPrefix=[jgitflow] -Dusername=\'${GIT_USERNAME}\' -Dpassword=\'${GIT_PASSWORD}\'"
      }
    }
  }

  post {
    always {
      notifySlack "${currentBuild.currentResult}", "#graylog-notifications"
    }
  }

}
